#!/bin/bash
# Docker Image Configuration
# This file defines the default Docker images and their SHA256 digests
# for reproducible builds.
#
# Generated by: release/update-docker-image.sh
# Last updated: 2026-01-02

# Default image repository
DEFAULT_IMAGE_REPOSITORY="leventehunyadi/md2conf"

# Default image version
DEFAULT_IMAGE_VERSION="latest"

# SHA256 digests for each image variant
# Format: sha256 hash without the 'sha256:' prefix
DEFAULT_IMAGE_SHA_ALL="PLACEHOLDER_ALL"
DEFAULT_IMAGE_SHA_MINIMAL="PLACEHOLDER_MINIMAL"
DEFAULT_IMAGE_SHA_MERMAID="PLACEHOLDER_MERMAID"
DEFAULT_IMAGE_SHA_PLANTUML="PLACEHOLDER_PLANTUML"

# Default image (full variant with SHA pinning)
DEFAULT_IMAGE="${DEFAULT_IMAGE_REPOSITORY}:${DEFAULT_IMAGE_VERSION}@sha256:${DEFAULT_IMAGE_SHA_ALL}"

# Export for use in other scripts
export DEFAULT_IMAGE_REPOSITORY
export DEFAULT_IMAGE_VERSION
export DEFAULT_IMAGE_SHA_ALL
export DEFAULT_IMAGE_SHA_MINIMAL
export DEFAULT_IMAGE_SHA_MERMAID
export DEFAULT_IMAGE_SHA_PLANTUML
export DEFAULT_IMAGE
