#!/usr/bin/env bash
# Docker Image Configuration
# This file defines the default Docker images and their SHA256 digests
# for reproducible builds.
#
# Generated by: release/update-docker-image.sh

# Default image repository
DEFAULT_IMAGE_REPOSITORY="codemedic/md2conf"

# Default image version
DEFAULT_IMAGE_VERSION="0.5.3"

# SHA256 digests for each image variant
# Format: sha256 hash without the 'sha256:' prefix
DEFAULT_IMAGE_SHA_ALL="18bf5eccf94fcf0636dcc45fa083aef02af03d1dc297d4a994f3144a7d4ff470"
DEFAULT_IMAGE_SHA_MINIMAL="44d7aac5f887889207605acc3d1b443f4ef9e6da3b4c1d4d6e57fe7ec3a13cc3"
DEFAULT_IMAGE_SHA_MERMAID="92f4f85ea1654917e8478e94f008b043adf2625e3430fe0862b01ca524aae854"
DEFAULT_IMAGE_SHA_PLANTUML="5f9bc71fc6c4c8bfe364aad446bd0d739b7bfa299188bb515207dabb61a8952f"

# Default image (full variant with SHA pinning)
DEFAULT_IMAGE="${DEFAULT_IMAGE_REPOSITORY}:${DEFAULT_IMAGE_VERSION}@sha256:${DEFAULT_IMAGE_SHA_ALL}"

# Export for use in other scripts
export DEFAULT_IMAGE_REPOSITORY
export DEFAULT_IMAGE_VERSION
export DEFAULT_IMAGE_SHA_ALL
export DEFAULT_IMAGE_SHA_MINIMAL
export DEFAULT_IMAGE_SHA_MERMAID
export DEFAULT_IMAGE_SHA_PLANTUML
export DEFAULT_IMAGE
