#!/usr/bin/env bash
# Docker Image Configuration
# This file defines the default Docker images and their SHA256 digests
# for reproducible builds.
#
# Generated by: release/update-docker-image.sh
# Last updated: 2026-01-03 01:37:25 UTC

# Default image repository
DEFAULT_IMAGE_REPOSITORY="codemedic/md2conf"

# Default image version
DEFAULT_IMAGE_VERSION="0.5.3"

# SHA256 digests for each image variant
# Format: sha256 hash without the 'sha256:' prefix
DEFAULT_IMAGE_SHA_ALL="2a8f65ce592b3c58b3e273c029213f0c28757679c67853294a5133db52fb4121"
DEFAULT_IMAGE_SHA_MINIMAL="335c52c8f47a7ffded446484903c3c2476d45e3cf7f01a7de271196b7892ac1a"
DEFAULT_IMAGE_SHA_MERMAID="7d770de246058a74c77f4060438d486c4d4cf80524f5e3ba3144dc2394de720a"
DEFAULT_IMAGE_SHA_PLANTUML="869f67f983bb165e30dc149bbed7da421c4f397c4a2591076073177d3ff2d221"

# Default image (full variant with SHA pinning)
DEFAULT_IMAGE="${DEFAULT_IMAGE_REPOSITORY}:${DEFAULT_IMAGE_VERSION}@sha256:${DEFAULT_IMAGE_SHA_ALL}"

# Export for use in other scripts
export DEFAULT_IMAGE_REPOSITORY
export DEFAULT_IMAGE_VERSION
export DEFAULT_IMAGE_SHA_ALL
export DEFAULT_IMAGE_SHA_MINIMAL
export DEFAULT_IMAGE_SHA_MERMAID
export DEFAULT_IMAGE_SHA_PLANTUML
export DEFAULT_IMAGE
