#!/usr/bin/env bash
# Docker Image Configuration
# This file defines the default Docker images and their SHA256 digests
# for reproducible builds.
#
# Generated by: release/update-docker-image.sh

# Default image repository
DEFAULT_IMAGE_REPOSITORY="codemedic/md2conf"

# Default image version
DEFAULT_IMAGE_VERSION="0.5.3"

# SHA256 digests for each image variant
# Format: sha256 hash without the 'sha256:' prefix
DEFAULT_IMAGE_SHA_ALL="412cc9d145b489b76bc9ef982923b93a79d214de8e17207abcd2ec703489e3fb"
DEFAULT_IMAGE_SHA_MINIMAL="0e805fa823cd1c94b4044c1d0ef3b32e62be84e3fbcd34fc93724245eaf55b1a"
DEFAULT_IMAGE_SHA_MERMAID="288ae175021d069a03ac038913b9f8b5666a169521b12b51f02ec7bdb914e501"
DEFAULT_IMAGE_SHA_PLANTUML="0510828218b2f99d3530d2719ae491f5d62d5ca2e0677589abc89a1dc7c516ad"

# Default image (full variant with SHA pinning)
DEFAULT_IMAGE="${DEFAULT_IMAGE_REPOSITORY}:${DEFAULT_IMAGE_VERSION}@sha256:${DEFAULT_IMAGE_SHA_ALL}"

# Export for use in other scripts
export DEFAULT_IMAGE_REPOSITORY
export DEFAULT_IMAGE_VERSION
export DEFAULT_IMAGE_SHA_ALL
export DEFAULT_IMAGE_SHA_MINIMAL
export DEFAULT_IMAGE_SHA_MERMAID
export DEFAULT_IMAGE_SHA_PLANTUML
export DEFAULT_IMAGE
