#!/bin/bash
set -euo pipefail

# Docker Image Update Automation
# Checks upstream Docker Hub for new image versions and updates image-config.sh
# with version tags and SHA256 digests.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || exit 1
readonly SCRIPT_DIR
readonly CONFIG_FILE="${SCRIPT_DIR}/image-config.sh"
readonly REPO="leventehunyadi/md2conf"

# Source shared functions
# shellcheck source=scripts/functions.sh
source "${SCRIPT_DIR}/functions.sh"

# Function to get SHA256 digest for a specific image tag
get_image_sha() {
    local repo="$1"
    local tag="$2"

    log_info "Fetching SHA256 for ${repo}:${tag}..."

    # Pull the image to get its digest
    if ! docker pull "${repo}:${tag}" >/dev/null 2>&1; then
        log_error "Failed to pull ${repo}:${tag}"
        return 1
    fi

    # Get the SHA256 digest
    local sha
    sha=$(docker inspect --format='{{index .RepoDigests 0}}' "${repo}:${tag}" | cut -d'@' -f2 | cut -d':' -f2)

    if [[ -z "$sha" ]]; then
        log_error "Failed to extract SHA256 for ${repo}:${tag}"
        return 1
    fi

    echo "$sha"
}

# Function to query Docker Hub API for latest tag
get_latest_version() {
    local repo="$1"

    log_info "Querying Docker Hub for latest version of ${repo}..."

    # Try to get the most recent versioned tag (v*.*.*)
    local latest_tag
    latest_tag=$(curl -s "https://hub.docker.com/v2/repositories/${repo}/tags/?page_size=100" | \
        jq -r '.results[].name' | \
        grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | \
        sort -V | \
        tail -n1)

    if [[ -z "$latest_tag" ]]; then
        log_warn "No versioned tag found, using 'latest'"
        latest_tag="latest"
    fi

    echo "$latest_tag"
}

# Function to update image-config.sh
update_config() {
    local version="$1"
    local sha_all="$2"
    local sha_minimal="$3"
    local sha_mermaid="$4"
    local sha_plantuml="$5"

    local timestamp
    timestamp=$(date +%Y-%m-%d)

    cat > "$CONFIG_FILE" <<EOF
#!/bin/bash
# Docker Image Configuration
# This file defines the default Docker images and their SHA256 digests
# for reproducible builds.
#
# Generated by: release/update-docker-image.sh
# Last updated: ${timestamp}

# Default image repository
DEFAULT_IMAGE_REPOSITORY="leventehunyadi/md2conf"

# Default image version
DEFAULT_IMAGE_VERSION="${version}"

# SHA256 digests for each image variant
# Format: sha256 hash without the 'sha256:' proceed
DEFAULT_IMAGE_SHA_ALL="${sha_all}"
DEFAULT_IMAGE_SHA_MINIMAL="${sha_minimal}"
DEFAULT_IMAGE_SHA_MERMAID="${sha_mermaid}"
DEFAULT_IMAGE_SHA_PLANTUML="${sha_plantuml}"

# Default image (full variant with SHA pinning)
DEFAULT_IMAGE="\${DEFAULT_IMAGE_REPOSITORY}:\${DEFAULT_IMAGE_VERSION}@sha256:\${DEFAULT_IMAGE_SHA_ALL}"

# Export for use in other scripts
export DEFAULT_IMAGE_REPOSITORY
export DEFAULT_IMAGE_VERSION
export DEFAULT_IMAGE_SHA_ALL
export DEFAULT_IMAGE_SHA_MINIMAL
export DEFAULT_IMAGE_SHA_MERMAID
export DEFAULT_IMAGE_SHA_PLANTUML
export DEFAULT_IMAGE
EOF

    log_info "Updated ${CONFIG_FILE}"
}

# Main execution
main() {
    local check_only=false
    local version=""

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --check)
                check_only=true
                shift
                ;;
            --version)
                version="$2"
                shift 2
                ;;
            --help)
                cat <<EOF
Usage: $0 [OPTIONS]

Update Docker image references with SHA256 digests.

Options:
  --check           Check for updates without modifying files
  --version <tag>   Use specific version tag (default: auto-detect latest)
  --help            Show this help message

Examples:
  # Check for latest version
  $0 --check

  # Update to latest version
  $0

  # Update to specific version
  $0 --version v0.5.3
EOF
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done

    # Check dependencies
    if ! command -v docker &> /dev/null; then
        log_error "Docker is required but not installed"
        exit 1
    fi

    if ! command -v jq &> /dev/null; then
        log_error "jq is required but not installed"
        exit 1
    fi

    # Determine version to use
    if [[ -z "$version" ]]; then
        version=$(get_latest_version "$REPO")
        log_info "Detected latest version: ${version}"
    else
        log_info "Using specified version: ${version}"
    fi

    # Get SHA256 digests for all variants
    log_info "Fetching SHA256 digests for all image variants..."

    sha_all=$(get_image_sha "$REPO" "${version}")
    sha_minimal=$(get_image_sha "$REPO" "${version}-minimal")
    sha_mermaid=$(get_image_sha "$REPO" "${version}-mermaid")
    sha_plantuml=$(get_image_sha "$REPO" "${version}-plantuml")

    # Display results
    echo ""
    log_info "Image Details:"
    echo "  Repository: ${REPO}"
    echo "  Version: ${version}"
    echo ""
    echo "  SHA256 Digests:"
    echo "    all:      ${sha_all}"
    echo "    minimal:  ${sha_minimal}"
    echo "    mermaid:  ${sha_mermaid}"
    echo "    plantuml: ${sha_plantuml}"
    echo ""

    if [[ "$check_only" == true ]]; then
        log_info "Check complete (no files modified)"
        exit 0
    fi

    # Update configuration
    update_config "$version" "$sha_all" "$sha_minimal" "$sha_mermaid" "$sha_plantuml"

    log_info "Update complete!"
    log_info "Next steps:"
    echo "  1. Review changes: git diff ${CONFIG_FILE}"
    echo "  2. Test locally: cd test/docs && ../../scripts/run-md2conf.sh"
    echo "  3. Commit changes: git add ${CONFIG_FILE} && git commit -m 'chore: update to md2conf ${version}'"
    echo "  4. Create release: git tag v1.x.x && git push --tags"
}

main "$@"
